from __future__ import absolute_import

# flake8: noqa

# import apis into api package
from nanonets.api.image_predict_api import ImagePredictApi
from nanonets.api.image_train_api import ImageTrainApi
from nanonets.api.image_upload_api import ImageUploadApi
from nanonets.api.image_model_api import ImageModelApi
from nanonets.api.multi_label_classification_model_api import MultiLabelClassificationModelApi
from nanonets.api.multi_label_classification_predict_api import MultiLabelClassificationPredictApi
from nanonets.api.multi_label_classification_train_api import MultiLabelClassificationTrainApi
from nanonets.api.multi_label_classification_upload_api import MultiLabelClassificationUploadApi
from nanonets.api.ocr_model_api import OCRModelApi
from nanonets.api.ocr_predict_api import OCRPredictApi
from nanonets.api.ocr_train_api import OCRTrainApi
from nanonets.api.ocr_upload_api import OCRUploadApi
from nanonets.api.object_model_api import ObjectModelApi
from nanonets.api.object_predict_api import ObjectPredictApi
from nanonets.api.object_train_api import ObjectTrainApi
from nanonets.api.object_upload_api import ObjectUploadApi
