# coding: utf-8

# flake8: noqa

"""
    NanoNets

    Welcome to the NanoNets API! You can use our API to build custom deep learning models for images.<br/> We have language bindings in Shell, Ruby, Golang, Java, C# and Python! You can view code examples in the dark area to the right, and you can switch the programming language for the examples with the tabs in the top right. <br/> In the documentation, you will find ready to fire code samples in these languages as well as detailed API specs for different endpoints.<br/> # Model Object A model Object has 3 attributes<br/> ### model_id <b>Definition:</b> Unique Id for the model <br/><br/> ### model_type <b>Definition:</b> Type of model. Possible values are: <br/> <table>     <tr>         <td>classification</td>         <td>Image classification model</td>     </tr>     <tr>         <td>localization</td>         <td>Object detection model</td>     </tr>     <tr>         <td>multilabelclassification</td>         <td>Multi label image classification model</td>     </tr>     <tr>         <td>ocr</td>         <td>OCR model</td>     </tr> </table> <br/>  ### state <b>Definition:</b>Current state of model. Possible values are::<br/> <table>     <tr>         <td>-1</td>         <td>Error in model training</td>     </tr>     <tr>         <td>0</td>         <td>Model created. No training data uploaded yet</td>     </tr>     <tr>         <td>1</td>         <td>Training data uploaded. Need to annotate data</td>     </tr>     <tr>         <td>2</td>         <td>Training data annotated. Need to start training</td>     </tr>     <tr>         <td>3</td>         <td>Model in training queue</td>     </tr>     <tr>         <td>4</td>         <td>Model currently training</td>     </tr>     <tr>         <td>5</td>         <td>Model hosted. Can be used for prediction</td>     </tr> </table>   # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: support@nanonets.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from nanonets.api.image_predict_api import ImagePredictApi
from nanonets.api.image_train_api import ImageTrainApi
from nanonets.api.image_upload_api import ImageUploadApi
from nanonets.api.image_model_api import ImageModelApi
from nanonets.api.multi_label_classification_model_api import MultiLabelClassificationModelApi
from nanonets.api.multi_label_classification_predict_api import MultiLabelClassificationPredictApi
from nanonets.api.multi_label_classification_train_api import MultiLabelClassificationTrainApi
from nanonets.api.multi_label_classification_upload_api import MultiLabelClassificationUploadApi
from nanonets.api.ocr_model_api import OCRModelApi
from nanonets.api.ocr_predict_api import OCRPredictApi
from nanonets.api.ocr_train_api import OCRTrainApi
from nanonets.api.ocr_upload_api import OCRUploadApi
from nanonets.api.object_model_api import ObjectModelApi
from nanonets.api.object_predict_api import ObjectPredictApi
from nanonets.api.object_train_api import ObjectTrainApi
from nanonets.api.object_upload_api import ObjectUploadApi
# import ApiClient
from nanonets.api_client import ApiClient
from nanonets.configuration import Configuration
# import models into sdk package
from nanonets.models.bndbox import Bndbox
from nanonets.models.create_new_modelrequest import CreateNewModelrequest
from nanonets.models.datum import Datum
from nanonets.models.object3 import Object3
from nanonets.models.upload_training_images_by_urlrequest import UploadTrainingImagesByUrlrequest
